version: "2"

services:
    modelapi: 
        image: modelapi:latest
        expose:
        - 8080
        ports:
        - 8080:8080
        volumes:
        - ./docker-compose/modelapi/data:/app/data