version: "2"

services:
    prometheus:
        image: docker.io/bitnami/prometheus:2
        volumes:
        - ./docker-compose/prometheus/conf:/opt/bitnami/prometheus/conf
        # for persisting prometheus data
        #- ./docker-compose/prometheus/data:/opt/bitnami/prometheus/data
        expose:
        - 9090
        ports:
        - 9090:9090

    grafana:
        image: docker.io/bitnami/grafana:7
        environment:
        - GF_SECURITY_ADMIN_PASSWORD=12345
        volumes:
        - ./docker-compose/grafana/conf/provisioning/datasources:/opt/bitnami/grafana/conf/provisioning/datasources
        - ./docker-compose/grafana/conf/provisioning/dashboards:/opt/bitnami/grafana/conf/provisioning/dashboards 
        - ./docker-compose/grafana/dashboards:/opt/bitnami/grafana/dashboards
        ports: 
        - 3000:3000
    
    minio:
        image: docker.io/bitnami/minio:2021.6.17
        environment: 
        - MINIO_ACCESS_KEY=minio-access-key
        - MINIO_SECRET_KEY=minio-secret-key
        expose:
        - 9000
        ports:
        - 9000:9000
        volumes:
        - ./docker-compose/minio/data:/data
    
    mlflow:
        build: ./docker-compose/mlflow/.
        environment: 
        - AWS_ACCESS_KEY_ID=minio-access-key
        - AWS_SECRET_ACCESS_KEY=minio-secret-key
        - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
        ports:
        - 5000:5000
        volumes:
        - ./docker-compose/mlflow/data:/data

    postgresql:
        image: "docker.io/bitnami/postgresql:11"
        environment:
        - ALLOW_EMPTY_PASSWORD=yes
        - POSTGRESQL_USERNAME=bn_keycloak
        - POSTGRESQL_DATABASE=bitnami_keycloak
        volumes:
        - ./docker-compose/keycloak/postgresql_data:/bitnami/postgresql
    keycloak:
        image: docker.io/bitnami/keycloak:latest
        ports:
        - "9100:8080"
        environment:
        - KEYCLOAK_CREATE_ADMIN_USER=true
        - KEYCLOAK_AUTH_CACHE_OWNERS_COUNT=3
        - KEYCLOAK_ADMIN_USER=user
        - KEYCLOAK_ADMIN_PASSWORD=bitnami
        - KEYCLOAK_MANAGEMENT_USER=manager
        - KEYCLOAK_MANAGEMENT_PASSWORD=bitnami1
        depends_on:
        - postgresql
    openldap:
        image: bitnami/openldap:2
        ports:
        - '1389:1389'
        - '1636:1636'
        environment:
        - LDAP_ADMIN_USERNAME=admin
        - LDAP_ADMIN_PASSWORD=adminpassword
        - LDAP_USERS=user01,user02
        - LDAP_PASSWORDS=password1,password2
        volumes:
        - ./docker-compose/keycloak/openldap_data:/bitnami/openldap