version: "2"

services:
    prometheus:
        image: docker.io/bitnami/prometheus:2
        volumes:
        - ./docker-compose/prometheus/conf:/opt/bitnami/prometheus/conf
        # for persisting prometheus data
        #- ./docker-compose/prometheus/data:/opt/bitnami/prometheus/data
        expose:
        - 9090
        ports:
        - 9090:9090

    grafana:
        image: docker.io/bitnami/grafana:7
        environment:
        - GF_SECURITY_ADMIN_PASSWORD=12345
        volumes:
        - ./docker-compose/grafana/conf/provisioning/datasources:/opt/bitnami/grafana/conf/provisioning/datasources
        - ./docker-compose/grafana/conf/provisioning/dashboards:/opt/bitnami/grafana/conf/provisioning/dashboards 
        - ./docker-compose/grafana/dashboards:/opt/bitnami/grafana/dashboards
        ports: 
        - 3000:3000
    
    minio:
        image: docker.io/bitnami/minio:2021.6.17
        environment: 
        - MINIO_ACCESS_KEY=minio-access-key
        - MINIO_SECRET_KEY=minio-secret-key
        expose:
        - 9000
        ports:
        - 9000:9000
        volumes:
        - ./docker-compose/minio/data:/data
    
    mlflow:
        build: ./docker-compose/mlflow/.
        environment: 
        - AWS_ACCESS_KEY_ID=minio-access-key
        - AWS_SECRET_ACCESS_KEY=minio-secret-key
        - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
        ports:
        - 5000:5000
        volumes:
        - ./docker-compose/mlflow/data:/data

    label-studio:
        #build: ./docker-compose/label-studio/.
        image: label-studio-headerauth:latest
        ports:
        - 9110:8080 
        volumes:
        - ./docker-compose/label-studio/data:/data

    voila:
        build: ./docker-compose/voila/.
        ports:
        - 9130:8888
        volumes:
        - ./docker-compose/voila/data:/data
    voila-oauth2-proxy:
        image: bitnami/oauth2-proxy:7.2.0
        # ports: 
        # - 9120:4180
        environment:
        - OAUTH2_PROXY_COOKIE_SECRET=A3ldwwx8j4g4MKnH51jD9g==
        - OAUTH2_PROXY_PROVIDER=keycloak-oidc
        - OAUTH2_PROXY_CLIENT_ID=voila-proxy
        - OAUTH2_PROXY_CLIENT_SECRET=57979fe9-a787-4b72-b974-b60cec67a9ef
        - OAUTH2_PROXY_OIDC_ISSUER_URL=http://localhost:9100/auth/realms/testrealm
        - OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL=true
        - OAUTH2_PROXY_ALLOWED_ROLE=reader # Optional, required realm role
        #- OAUTH2_PROXY_ALLOWED_ROLE=<client id>:<client role name> # Optional, required client role
        - OAUTH2_PROXY_REDIRECT_URL=http://localhost:4180/oauth2/callback
        - OAUTH2_PROXY_EMAIL_DOMAINS=*
        #- OAUTH2_PROXY_SCOPE='openid roles'
        - OAUTH2_PROXY_PASS_USER_HEADERS=true
        #- OAUTH2_PROXY_PASS_ACCESS_TOKEN=true
        #- OAUTH2_PROXY_OIDC_GROUPS_CLAIM=group2
        - OAUTH2_PROXY_SET_XAUTHREQUEST=true
        #- KEYCLOAK_GROUP=<first_allowed_user_group>
        command: ["--upstream=http://localhost:9140/", "--http-address=0.0.0.0:4180", "--pass-user-headers=true", "--pass-access-token=true"]
        # command: ["--http-address=0.0.0.0:4180", "--pass-user-headers=true", "--pass-access-token=true"]
        network_mode: host
        # extra_hosts:
        # - "host.docker.internal:host-gateway"
    nginx:
        image: docker.io/bitnami/nginx:1.21
        ports:
        - 9140:9140
        volumes:
        - ./docker-compose/nginx/voila.conf:/opt/bitnami/nginx/conf/server_blocks/voila.conf:ro
        # network_mode: host

    echo:
        image: docker.io/brndnmtthws/nginx-echo-headers:latest
        ports:
        - 9150:8080 