version: "2"

services:
    prometheus:
        image: docker.io/bitnami/prometheus:2
        volumes:
        - ./docker-compose/prometheus/conf:/opt/bitnami/prometheus/conf
        # for persisting prometheus data
        #- ./docker-compose/prometheus/data:/opt/bitnami/prometheus/data
        expose:
        - 9090
        ports:
        - 9090:9090

    grafana:
        image: docker.io/bitnami/grafana:7
        environment:
        - GF_SECURITY_ADMIN_PASSWORD=12345
        volumes:
        - ./docker-compose/grafana/conf/provisioning/datasources:/opt/bitnami/grafana/conf/provisioning/datasources
        - ./docker-compose/grafana/conf/provisioning/dashboards:/opt/bitnami/grafana/conf/provisioning/dashboards 
        - ./docker-compose/grafana/dashboards:/opt/bitnami/grafana/dashboards
        ports: 
        - 3000:3000
    
    minio:
        image: docker.io/bitnami/minio:2021.6.17
        environment: 
        - MINIO_ACCESS_KEY=minio-access-key
        - MINIO_SECRET_KEY=minio-secret-key
        expose:
        - 9000
        ports:
        - 9000:9000
        volumes:
        - ./docker-compose/minio/data:/data
    
    mlflow:
        build: ./docker-compose/mlflow/.
        environment: 
        - AWS_ACCESS_KEY_ID=minio-access-key
        - AWS_SECRET_ACCESS_KEY=minio-secret-key
        - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
        ports:
        - 5000:5000
        volumes:
        - ./docker-compose/mlflow/data:/data

    label-studio:
        build: ./docker-compose/label-studio/.
        ports:
        - 9110:8080 
        volumes:
        - ./docker-compose/label-studio/data:/data

    voila:
        build: ./docker-compose/voila/.
        ports:
        - 9130:8888
        volumes:
        - ./docker-compose/voila/data:/data
    voila-oauth2-proxy:
        image: bitnami/oauth2-proxy:7
        # ports: 
        # - 9120:4180
        environment:
        - OAUTH2_PROXY_PROVIDER=keycloak
        - OAUTH2_PROXY_CLIENT_ID=voila-proxy
        - OAUTH2_PROXY_CLIENT_SECRET=57979fe9-a787-4b72-b974-b60cec67a9ef
        - OAUTH2_PROXY_LOGIN_URL=http://localhost:9100/auth/realms/testrealm/protocol/openid-connect/auth
        - OAUTH2_PROXY_REDEEM_URL=http://localhost:9100/auth/realms/testrealm/protocol/openid-connect/token
        - OAUTH2_PROXY_PROFILE_URL=http://localhost:9100/auth/realms/testrealm/protocol/openid-connect/userinfo
        - OAUTH2_PROXY_VALIDATE_URL=http://localhost:9100/auth/realms/testrealm/protocol/openid-connect/userinfo
        - OAUTH2_PROXY_UPSTREAMS=http://localhost:9140/
        - OAUTH2_PROXY_REDIRECT_URL=http://localhost:4180/oauth2/callback
        - OAUTH2_PROXY_EMAIL_DOMAINS=*
        - OAUTH2_PROXY_SCOPE=email
        - OAUTH2_PROXY_COOKIE_SECRET=A3ldwwx8j4g4MKnH51jD9g==
        - OAUTH2_PROXY_PASS_USER_HEADERS=true
        #- KEYCLOAK_GROUP=<first_allowed_user_group>
        command: ["--upstream=http://localhost:9140/", "--http-address=0.0.0.0:4180", "--pass-user-headers=true"]
        network_mode: host

    nginx:
        image: docker.io/bitnami/nginx:1.21
        ports:
        - 9140:80
        volumes:
        - ./docker-compose/nginx/voila.conf:/opt/bitnami/nginx/conf/server_blocks/voila.conf:ro

    # nginx:
    #     image: docker.io/brndnmtthws/nginx-echo-headers:latest
    #     ports:
    #     - 9140:8080 

    postgresql:
        image: "docker.io/bitnami/postgresql:11"
        environment:
        - ALLOW_EMPTY_PASSWORD=yes
        - POSTGRESQL_USERNAME=bn_keycloak
        - POSTGRESQL_DATABASE=bitnami_keycloak
        volumes:
        - ./docker-compose/keycloak/postgresql_data:/bitnami/postgresql
    keycloak:
        image: docker.io/bitnami/keycloak:latest
        ports:
        - "9100:8080"
        environment:
        - KEYCLOAK_CREATE_ADMIN_USER=true
        - KEYCLOAK_AUTH_CACHE_OWNERS_COUNT=3
        - KEYCLOAK_ADMIN_USER=user
        - KEYCLOAK_ADMIN_PASSWORD=bitnami
        - KEYCLOAK_MANAGEMENT_USER=manager
        - KEYCLOAK_MANAGEMENT_PASSWORD=bitnami1
        depends_on:
        - postgresql

    openldap:
        image: bitnami/openldap:2
        ports:
        - '1389:1389'
        - '1636:1636'
        environment:
        - LDAP_ADMIN_USERNAME=admin
        - LDAP_ADMIN_PASSWORD=adminpassword
        # - LDAP_USERS=user01,user02
        # - LDAP_PASSWORDS=password1,password2
        - LDAP_CUSTOM_LDIF_DIR=/bitnami/ldap_ldif
        volumes:
        - ./docker-compose/keycloak/openldap_data:/bitnami/openldap
        - ./docker-compose/keycloak/ldap_ldif:/bitnami/ldap_ldif