name: mlops
dependencies:
  - python=3.8
  - ipykernel
  - pip
  - dvc-s3=2.1
  - prometheus-fastapi-instrumentator
  - fastapi
  - uvicorn
  - scikit-learn=1.1
  - doit
  - pandas
  - mlflow
  - minio
  - fairlearn
  - cloudpickle
  - lime
  - eli5
  - matplotlib
  - rise
  - pathspec=0.9 # fix https://github.com/iterative/dvc/issues/8217
  - pip
  - pip: 
    - openapi-python-client

