name: mlops
channels:
  - conda-forge
dependencies:
  - python=3.8
  - ipykernel=5.5.5
  - pip=21.1.2
  - dvc-s3=2.1.0
  - prometheus-fastapi-instrumentator
  - fastapi
  - uvicorn
  - scikit-learn
  - doit
  - pandas
  - mlflow
  - minio
  - fairlearn
  - cloudpickle
  - lime
  - eli5
  - matplotlib
  - pip
  - pip: 
    - openapi-python-client

