name: mlops
channels:
  - defaults
  - conda-forge
dependencies:
  - dvc-s3=2.1
  - fairlearn
  - fastapi
  - ipykernel
  - lime
  - matplotlib
  - minio
  - mlflow
  - pandas
  - pip
  - prometheus-fastapi-instrumentator
  - python=3.10
  - scikit-learn=1.1
  - uvicorn
#  - rise
  - pip
  - pip: 
    - openapi-python-client

