{
 "title": "Model Score",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Model", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avg. Score in last 10 min",
   "type": "gauge",
   "description": "MIttelerer Sentiment Score",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(mlops_model_model_score_sum[10m])/increase(mlops_model_model_score_count[10m])"
    }
   ]
  },
  {
   "title": "Label",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(mlops_model_label_total[$__interval])) by (label)",
     "legendFormat": "{{sentiment}}"
    }
   ]
  },
  {
   "title": "Score Distribution",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(mlops_model_model_score_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Drift",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(mlops_model_drift_total[$__interval])) by (drift_label)",
     "legendFormat": "{{drift_label}}"
    }
   ]
  },
  {
   "title": "Outlier Score",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(mlops_model_outlier_score_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Avg Outlier Score",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(increase(mlops_model_outlier_score_sum[10m])/increase(mlops_model_outlier_score_count[10m]))-1",
     "legendFormat": "outlier score"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(increase(mlops_model_http_request_duration_seconds_bucket{handler=\"/predict\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mlops_model_http_response_size_bytes_count{handler=\"/predict\"}[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}